### PR TITLE
BXMSPROD-21: added one line for testing PRs jobs migration

### PR DESCRIPTION
**Pull request by mbiarnes**
please don't merge this PR - this is only for testing

### CODE REVIEW

**Comment by pszubiak** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@mbiarnes can we close this PR?

**Pull request closed without merging**
